[package]
name = "hostcmd"
version = "0.0.2"
edition = "2024"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
axum = { version = "0.8", features = ["ws"] }
tokio-tungstenite = "0.26"
futures-util = "0.3"
bytes = "1.0"
clap = { version = "4.6.0", features = ["derive", "env"] }
anyhow = "1"
nix = { version = "0.30", features = ["hostname", "process", "signal"] }
